{% set name = "webp" %}
{% set version = "1.2.1" %}
{% set sha256 = "808b98d2f5b84e9b27fdef6c5372dac769c3bda4502febbfa5031bd3c4d7d018" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  fn:  lib{{ name }}-{{ version }}.tar.gz
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/{{name}}/lib{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libwebp
    - {{ pin_subpackage('libwebp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - libtool  # [unix]
  host:  # [unix]
    - jpeg  # [unix]
    - libpng  # [unix]
    - libtiff  # [unix]
    - giflib  # [unix]

test:
  source_files:
    - examples/test.webp
  commands:
    - cwebp -longhelp  # [unix]
    - dwebp -h  # [unix]
    - webpinfo -version  # [unix]
    - dwebp examples/test.webp  # [not win]
    - dwebp examples\\test.webp  # [win]
    - test -f $PREFIX/lib/libwebp.a  # [unix]
    - test -f $PREFIX/lib/libwebp.dylib  # [osx]
    - test -f $PREFIX/lib/libwebp.so  # [linux]
    - test -f $PREFIX/bin/cwebp  # [unix]
    - test -f $PREFIX/bin/dwebp  # [unix]
    - test -f $PREFIX/include/webp/decode.h  # [unix]
    - test -f $PREFIX/include/webp/encode.h  # [unix]
    - test -f $PREFIX/include/webp/types.h  # [unix]
    - if not exist %LIBRARY_LIB%\\libwebp.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libwebpdecoder.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\cwebp.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\dwebp.exe exit 1  # [win]
    - if not exist %LIBRARY_INC%\\webp\\decode.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\webp\\encode.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\webp\\types.h exit 1  # [win]

about:
  home: https://developers.google.com/speed/webp/
  license: Google
  license_file: COPYING
  summary: "WebP image library"
  description: |
    WebP is a method of lossy and lossless compression that can be used on a large variety of photographic,
    translucent and graphical images found on the web. The degree of lossy compression is adjustable so a
    user can choose the trade-off between file size and image quality.
  doc_url: https://developers.google.com/speed/webp/docs/using
  dev_url: https://chromium.googlesource.com/webm/libwebp

extra:
  recipe-maintainers:
    - dschreij
