# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Cvhi/64gWsc0FmckGy/wK4/suvwBfp+HxxWJ8x6Jgz2YqyMs2Vv5lnohoA7xAMzdmSL6Riti/EsEM9d3ryiCIHS7L/ACnCJo6zlYiAhZL1lE8fYalGkSgu83ARzOX7GZ8tj8Hu942m+fPZSx90R3Gc0XVX7EEgFYqYOsEO9flK2cG0mklC0yycPD7UGfAg6ZXVr3gHS+oG1U6dyYq2eFJqNqwGPR0/kVmLVXNO9C+wvwwLq1zw8fCYVESxuLUCZs2NyfYBnnIhSdE38Erq7zENPzfH3TZ6baln5h47Op4Zq/4Hp/iQbaAWiZad5cD69rISyfOrXuTbxtnHu2QnmM/KE017OY1gsdzYlen6RqNsHiy43kHce78fUy8l5Mr0FzjMObTUzaOOph/9g8bIuSHUwHWnEZ0q2gAu/N1uXxdV5SMQzAHBUBrPIQJ7nX5aBkq0thdLHV0OGHudoP26mylH8ejNjq5nPF9jLeHAtQ4J+vVKWtEQcH1vOE787yu0F2TAQv/4IoFd42t2Ess+sEfTFKoj7eOTG9+VfRxIqmUAETCSWva4slhvTRecvISmgLAisrKIPDZ5DztfPL9EzXoTq5XIWQpxWSO1FAkJzejlu7WSb1dV1bJ+BczvAyZ/pgoKGje9CLHPyYcn7QUJYwjd1kcw+COtlUuMf6UdqYEQc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
