travis:
  secure:
    BINSTAR_TOKEN: WjgWmMUIdR4xlW7j2fPeq+rrLqV29QaVmRs6/sdqt4YwRXtbi2ImNxf2Vtjadz5UjLCs5WJnT8QXs1x/EIm83xtuxege3Eaqb0uvVSUygFI3pqDUKK4CAlRmrdqtnGxO52fCPiu4XVnBRjs+dC+hY3iGcUA7cl+ogIdak67d4grhnlhBuwKMbMtiPjiSDSJ/srPV52NExqWZSMa0QO/tFVOd2UZoi/wKVR6KfEXFaxH+Qu9ZqxltUfIQ3qwo6HpZ0NF51aBGIS/5g8r3YKi/JrV/cQXpwcxOn99Ermg4ylhIUph0ag/l6yU3CAZJiZV/vhk9tD/H1G8Xx5Std2HPL+iPhCKGjcF+zB024XCzLJRqwtaldFIXfBFGnlzr8cV6t2t5bPzw38AdHtd4VdtuonoERiWorRnM90+Q8bPVVHqtP7NSJVG38K9QKQ2TCL6RKy4uWhPdAwg2n+dNg81ms5Rvfn/JZnDLxT6X+cLiaXq6shbbb3tGWgYaAmKlAHF7fd+kvQsZhlqQZ6GgIyhm/DE8TGyaxHNFM6zSr3IdXDHKJI3LKAloOUkSzd+K5TXujhIpQ4UhKBXpPKGgnmPaZvRJMSakIkIlWorbm579R7YbIBk95SAsv65/Vnu4imKg7Kwm79/DOt/OP0pkQWGfnasRNKAzA45idsQHns5xEE4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
