travis:
  secure:
    BINSTAR_TOKEN: k8V8P3PKOk3Ok39RXHi+l/mr1mh8v7mR+c7vVbiNT4m6e+hmwmUtST2qsiKpRqTBEoazI6B86RVgOn1Em0P4BjaEjMA85amMLlajeu44QBC8suw2l7uVYOkeH660nZL1ta2ezsKsAJiocObdvI9BXNgs5vmOl9PTwtWB4nmSWAXiHeord+f6jGoLMxMcWgwRjYMgUMXZM8rKzLZoamuBLsmkJ21/nSxyfbgdhwY1BTUnTeB4jleJINWABpas45L9rhCpekgSwjpYfG4+hqOAD4JN/CV3htkg4xIAQ33Y+cJD5EY0EUKosm7iiNTN+bpFgv/MM1+XJEAoum3Nl5aESl3H9pRQURxb18x7OdMEiZNfHwPJ8F0Q9TZUhT9y/qNdOy0pikj8env+grTIzAhAIpqQrTpJvpEV/50Dkrf/joR/OcO9d/0wRDXbBkpC1VEt0/vrAX7jUjDOhI/DKwiRqMm/zs8cnOdvYOigMvcffqZuUvkYwEXY8Nnqx7xwU2caSH0rTGbJsUsWaSJ5UQKL43MmHDphIGGnFx0UDH9crC1FPZB1FVYP2lboM5GBvV7Fa9goP5fnC6GQYKHuYwQ9RH7nP2OQr/LLtHYrLHS5mzdFojV7y8nTFjLCCyAzLYTQYIxvHi8aNDkMPj7xjofsuOh/DyUvrwqZdJYZH0CSnEY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
